[package]
name = "gmi-launchpad"
version = "0.1.0"
description = "GMI NFT Launchpad - Solana Anchor Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gmi_launchpad"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
operator-registry = { path = "../operator-registry", features = ["cpi"] }
